/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projettelephone;

import javax.swing.*;


/**
 *
 * @author ibrahim
 */
public class AppelSortant extends javax.swing.JPanel {
    private IAppel listener;
    
    /**
     * Creates new form AppelSortant
     */
    public AppelSortant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroSortant = new javax.swing.JLabel();
        couper = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        numeroSortant.setBackground(new java.awt.Color(0, 0, 0));
        numeroSortant.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numeroSortant.setForeground(new java.awt.Color(255, 255, 255));
        numeroSortant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroSortant.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        couper.setBackground(new java.awt.Color(255, 51, 51));
        couper.setText("couper");
        couper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(couper, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(numeroSortant, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(numeroSortant, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(couper, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void couperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couperActionPerformed
        // TODO add your handling code here:
        this.listener.onClickFermer(((JFrame) SwingUtilities.getWindowAncestor(this)).getTitle());
    }//GEN-LAST:event_couperActionPerformed

    public void setNumeroSortant(String numero) {
        numeroSortant.setText(numero);
    }
    
    public void setListener(IAppel listener) {
        this.listener = listener;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton couper;
    private javax.swing.JLabel numeroSortant;
    // End of variables declaration//GEN-END:variables
}
