/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projettelephone;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Eclipse
 */
public class ContactsEnregistres extends javax.swing.JPanel {
    private IAppel listener;
    private List<Contact> contacts;
    private DefaultListModel<String> model = new DefaultListModel<String>();

    /**
     * Creates new form ContactsEnregistres
     */
    public ContactsEnregistres() {
        initComponents();
    }
    
    private void afficherListe() {
        model = new DefaultListModel<String>();
        contacts.forEach(item -> {
            model.addElement("Nom: " + item.getNom() + " Numero: " + item.getNumero());
        });
        
        listeContacts.setModel(model);
    }
    
    public void setListContacts(List<Contact> contacts) {
        this.contacts = contacts;
        afficherListe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFermer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeContacts = new javax.swing.JList<>();

        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listeContacts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 71, Short.MAX_VALUE)
                .addComponent(btnFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFermer, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        listener.onClickFermerHistorique(((JFrame) SwingUtilities.getWindowAncestor(this)).getTitle());
    }//GEN-LAST:event_btnFermerActionPerformed

    public void setListener(IAppel listener) {
        this.listener = listener;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermer;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listeContacts;
    // End of variables declaration//GEN-END:variables

}
